version: "3.9"

services:
  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    env_file:
      - .env  # Указываем файл для переменных окружения

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"  # Подтягиваем из .env
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # Подтягиваем из .env
      POSTGRES_DB: "${POSTGRES_DB}"  # Подтягиваем из .env
    ports:
      - "5432:5432"
    env_file:
      - .env  # Указываем файл для переменных окружения

volumes:
  postgres_data:
