"""Second migration

Revision ID: 055dce7c0257
Revises: f89c65879b20
Create Date: 2024-11-20 10:56:22.057074

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "055dce7c0257"
down_revision = "f89c65879b20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
