"""Remove Logs table1

Revision ID: 9a6484359821
Revises: ecd5157b2124
Create Date: 2024-11-21 14:57:49.289962

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a6484359821"
down_revision = "ecd5157b2124"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
