"""Third migration

Revision ID: f32fce9faa1a
Revises: 055dce7c0257
Create Date: 2024-11-20 12:16:56.062587

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f32fce9faa1a"
down_revision = "055dce7c0257"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("catalog_type_key", "catalog", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("catalog_type_key", "catalog", ["type"])
    # ### end Alembic commands ###
